spring.application.name=smartParkingAndReservation

# DataSource configuration
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:smartParking
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# H2 Console (for development)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Servlet configuration for file upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=100MB
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

user.image.directory=c:\\Users\\viswa\\OneDrive\\Documents\\TK181219 - Vinay - Smart Online Parking And Reservation System\\TK163983 - Smart Online Parking And Reservation System\\CODE\\server\\src\\main\\resources\\static\\images

